# encoding: UTF-8

control 'C-1.6.7' do
  title 'Ensure system wide crypto policy disables EtM for ssh'
  desc  "
    Encrypt-then-MAC (EtM) - The ciphertext is generated by encrypting the plaintext and then appending a MAC of the encrypted plaintext

    There is an effective attack against SSH's use of Cypher-Block-Chaining (CBC) with Encrypt-then-MAC as referenced in `CVE-2023-48795`
  "
  desc  'rationale', "
    Encrypt-then-MAC (EtM) - The ciphertext is generated by encrypting the plaintext and then appending a MAC of the encrypted plaintext

    There is an effective attack against SSH's use of Cypher-Block-Chaining (CBC) with Encrypt-then-MAC as referenced in `CVE-2023-48795`
  "
  desc  'check', "
    - IF - `CVE-2023-48795` has been addressed or if CBC is disabled for OpenSSH server this recommendation is not needed.

    Run the following command to verify `EtM` is disabled for `SSH`:

    ```
    # grep -Psi -- '^\\h*etm\\b' /etc/crypto-policies/state/CURRENT.pol
    ```

    Verify output includes either:

    ```
    etm@libssh = DISABLE_ETM
    etm@openssh-client = DISABLE_ETM
    etm@openssh-server = DISABLE_ETM
    ```

    - OR -

    ```
    etm = DISABLE_ETM
    ```

    Note: The ability to disable EtM through system wide crypto policy was added in version 9.3
  "
  desc  'fix', "
    Note: 
    - The commands below are written for the included `DEFAULT` system-wide crypto policy. If another policy is in use and follows local site policy, replace `DEFAULT` with the name of your system-wide crypto policy.
    - `EtM` can be turned off globally by using the argument `etm` opposed to `etm@SSH`
    - Multiple subpolicies may be assigned to a policy as a colon separated list. e.g. `DEFAULT:NO-SHA1:NO-SSHCBC`
    - Subpolicies:
      - Not included in the `update-crypto-policies --set` command will not be applied to the system wide crypto policy.
      - must exist before they can be applied to the system wide crypto policy.
      -  `.pmod` file filenames must be in all upper case, upper case, e.g. `NO-SSHCHACHA20.pmod`, or they will not be read by the `update-crypto-policies  --set` command.

    - IF - `CVE-2023-48795` has been addressed, and it meets local site policy, this recommendation may be skipped.

    Create or edit a file in `/etc/crypto-policies/policies/modules/` ending in `.pmod` and add or modify the following line:

    ```
    etm@SSH = DISABLE_ETM # This disables EtM for openSSH and libssh
    ```

    _Example:_

    ```
    # printf '%s\\n' \"# This is a subpolicy to disable Encrypt then MAC\" \"# for the SSH protocol (libssh and OpenSSH)\" \"etm@SSH = DISABLE_ETM\" >> /etc/crypto-policies/policies/modules/NO-SSHETM.pmod
    ```

    Run the following command to update the system-wide cryptographic policy

    ```
    # update-crypto-policies --set : : : ```

    _Example:_

    ```
    # update-crypto-policies --set DEFAULT:NO-SHA1:NO-WEAKMAC:NO-SSHCBC:NO-SSHCHACHA20:NO-SSHETM
    ```

    Run the following command to reboot the system to make your cryptographic settings effective for already running services and applications:

    ```
    # reboot
    ```
  "
  tag severity:              'medium'
  tag severity_source:       'unassessed'
  tag nist:                  ['SC-8', 'AC-8 a']
  tag ksi:                   ['KSI-CNA-MAT', 'KSI-CNA-ULN', 'KSI-SVC-SIN']
  tag nist_r4:               ['SC-8']
  tag cci:                   ['CCI-002418', 'CCI-000051']
  tag cis_rid:               '1.6.7'
  tag cis_number:            '1.6.7'
  tag cis_benchmark:         'CIS Red Hat Enterprise Linux 9 Benchmark v2.0.0'
  tag cis_rule_id:           'SV-010607r1_rule'
  tag cis_version:           '2.0.0'
  tag cis_level:             1
  tag cis_scored:            true
  tag implementation_status: 'implemented'

  impact 0.5
  describe command(%q{grep -Psi -- '^\h*etm\b' /etc/crypto-policies/state/CURRENT.pol 2>/dev/null}) do
    its('stdout') { should match(/DISABLE_ETM/) }
  end
end