# encoding: UTF-8

control 'C-6.2.1.3' do
  title 'Ensure journald log file rotation is configured'
  desc  "
    Journald includes the capability of rotating log files regularly to avoid filling up the system with logs or making the logs unmanageably large. The file `/etc/systemd/journald.conf` is the configuration file used to specify how logs generated by Journald should be rotated.

    By keeping the log files smaller and more manageable, a system administrator can easily archive these files to another system and spend less time looking through inordinately large log files.
  "
  desc  'rationale', "
    Journald includes the capability of rotating log files regularly to avoid filling up the system with logs or making the logs unmanageably large. The file `/etc/systemd/journald.conf` is the configuration file used to specify how logs generated by Journald should be rotated.

    By keeping the log files smaller and more manageable, a system administrator can easily archive these files to another system and spend less time looking through inordinately large log files.
  "
  desc  'check', "
    Review `/etc/systemd/journald.conf` and files in the `/etc/systemd/journald.conf.d/` directory ending in `.conf`. Verify logs are rotated according to site policy. 

    Run the following command and ensure logs are rotated according to site policy:
    ```
    # systemd-analyze cat-config systemd/journald.conf | grep -E '(SystemMaxUse|SystemKeepFree|RuntimeMaxUse|RuntimeKeepFree|MaxFileSec)'
    ```

    ```
    SystemMaxUse=
    SystemKeepFree=
    RuntimeMaxUse=
    RuntimeKeepFree=
    MaxFileSec=
    ```
  "
  desc  'fix', "
    Edit `/etc/systemd/journald.conf` or a file ending in `.conf` the `/etc/systemd/journald.conf.d/` directory. Set the following parameters in the `[Journal]` section to ensure logs are rotated according to site policy. The settings should be carefully understood as there are specific edge cases and prioritization of parameters.

    _Example Configuration_
    ```
    [Journal]
    SystemMaxUse=1G
    SystemKeepFree=500M
    RuntimeMaxUse=200M
    RuntimeKeepFree=50M
    MaxFileSec=1month
    ```

    Note: If these settings appear in a canonically later file, or later in the same file, the setting will be overwritten
  "
  impact 0.5
  tag severity:              'medium'
  tag nist:                  ['AC-2 f', 'IA-2 (2)', 'AU-2 a']
  tag cci:                   ['CCI-000011', 'CCI-000766', 'CCI-000123']
  tag cis_rid:               '6.2.1.3'
  tag cis_number:            '6.2.1.3'
  tag cis_benchmark:         'CIS Red Hat Enterprise Linux 9 Benchmark v2.0.0'
  tag cis_rule_id:           'SV-06020103r1_rule'
  tag cis_version:           '2.0.0'
  tag cis_level:             1
  tag cis_scored:            true
  tag implementation_status: 'implemented'

  impact 0.5
  describe command(%q{grep -rhEi '^\s*(SystemMaxUse|RuntimeMaxUse|SystemMaxFileSize|SystemKeepFree)\s*=' /etc/systemd/journald.conf /etc/systemd/journald.conf.d/ 2>/dev/null}) do
    its('stdout') { should match(/\S/) }
  end
end